name: CI
on:
  - push
  - pull_request
jobs:
  testMKLjl:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.0'
          - '1.3'
#           - 'nightly'
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
        arch:
          - x64
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - run: julia -e 'using Pkg; Pkg.develop(PackageSpec(url=\"https://github.com/JuliaComputing/MKL.jl\")); Pkg.instantiate()'
        if: matrix.os == 'windows-latest'
      - run: julia -e 'using Pkg; Pkg.develop(PackageSpec(url="https://github.com/JuliaComputing/MKL.jl")); Pkg.instantiate()'
        if: matrix.os != 'windows-latest'
      - uses: julia-actions/julia-buildpkg@latest
      - run: julia -e 'using Pkg; Pkg.status()'
      - uses: julia-actions/julia-runtest@latest
#       - run: julia --color=yes --check-bounds=yes -e 'using Pkg; Pkg.test("IntelVectorMath", coverage=true)'
#         if: matrix.os != 'windows-latest'
#       - run: julia --color=yes --check-bounds=yes -e 'using Pkg; Pkg.test(\"IntelVectorMath\", coverage=true)'
#         if: matrix.os == 'windows-latest'

#   testAptMKL:
#     name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }}
#     runs-on: ${{ matrix.os }}
#     strategy:
#       fail-fast: false
#       matrix:
#         version:
#           - '1.0'
# #           - '1.3'
# #           - 'nightly'
#         os:
#           - ubuntu-latest
#           - macOS-latest
#         arch:
#           - x64
#     steps:
#       - run: curl https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS-2019.PUB > GPG-PUB-KEY-INTEL-SW-PRODUCTS-2019.PUB
#       - run: apt-key add GPG-PUB-KEY-INTEL-SW-PRODUCTS-2019.PUB
#       - run: rm GPG-PUB-KEY-INTEL-SW-PRODUCTS-2019.PUB
#       - run: sh -c 'echo deb https://apt.repos.intel.com/mkl all main > /etc/apt/sources.list.d/intel-mkl.list'
#       - run: apt-get update
#       - run: apt-get install -y intel-mkl-64bit-2019.4-070
#       - run: source /opt/intel/mkl/bin/mklvars.sh intel64
